export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const HANDLE_REMOVE = "HANDLE_REMOVE";
export const HANDLE_EDIT = "HANDLE_EDIT";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_TOGGLE_SIDEBAR = "SET_TOGGLE_SIDEBAR";
